services:
  - type: web
    name: nissan-abi
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      echo "from django.db import connection
      from django.core.management import call_command
      
      with connection.cursor() as cursor:
          cursor.execute('DROP SCHEMA public CASCADE;')
          cursor.execute('CREATE SCHEMA public;')
      
      call_command('makemigrations')
      call_command('makemigrations', 'cars')
      call_command('migrate', '--run-syncdb')
      call_command('migrate')" > migrate.py
      python migrate.py
      python manage.py collectstatic --noinput
    startCommand: gunicorn bmw_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: DJANGO_SETTINGS_MODULE
        value: bmw_project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /
    autoDeploy: true
