services:
  - type: web
    name: nissan-abi
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bmw_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: DJANGO_SETTINGS_MODULE
        value: bmw_project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    healthCheckPath: /
    autoDeploy: true 