services:
  - type: web
    name: nissan-abi
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python -m daphne -b 0.0.0.0 -p $PORT bmw_project.asgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: DJANGO_SETTINGS_MODULE
        value: bmw_project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    healthCheckPath: /
    autoDeploy: true 