# Generated by Django 5.2 on 2025-04-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('michelin', 'میشلن'), ('bridgestone', 'بریجستون'), ('continental', 'کنتیننتال'), ('pirelli', 'پیرلی'), ('goodyear', 'گودیر'), ('dunlop', 'دانلوپ'), ('yokohama', 'یوکوهاما'), ('hankook', 'هانکوک')], max_length=50, verbose_name='برند')),
                ('model', models.CharField(max_length=100, verbose_name='مدل')),
                ('size', models.CharField(max_length=20, verbose_name='سایز')),
                ('season', models.CharField(choices=[('summer', 'تابستانی'), ('winter', 'زمستانی'), ('all_season', 'چهار فصل')], max_length=20, verbose_name='فصل')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='tires/', verbose_name='تصویر')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'لاستیک',
                'verbose_name_plural': 'لاستیک\u200cها',
            },
        ),
    ]
