# Generated by Django 5.2 on 2025-04-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_tire'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('sedan', 'سدان'), ('coupe', 'کوپه'), ('suv', 'شاسی بلند'), ('sport', 'اسپرت')], default='sedan', max_length=20, verbose_name='نوع خودرو'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='brand',
            field=models.CharField(choices=[('michelin', 'میشلن'), ('bridgestone', 'بریجستون'), ('continental', 'کنتیننتال'), ('pirelli', 'پیرلی'), ('goodyear', 'گودیر'), ('dunlop', 'دانلوپ'), ('yokohama', 'یوکوهاما'), ('hankook', 'هانکوک'), ('nokian', 'نوکیان'), ('kavir', 'کویر تایر'), ('yazd', 'یزد تایر')], max_length=50, verbose_name='برند'),
        ),
    ]
